version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yml --awspipelinestack-artifactbucket-1t1f9uir8ukz1 --output-template-file packaged.yml

artifacts:
  type: zip
  files:
    - template.yml
    - packaged.yml
